image: docker:stable
variables:
  DOCKER_DRIVER: overlay2
  IMAGE: vrutkovs/quedar
  DOCKER_USERNAME: vrutkovs
  CACHE: yes
services:
- docker:dind

before_script:
- docker login -u="GITLAB_USER_ID" -p="$GITLAB_TOKEN" registry.gitlab.com
- docker pull registry.gitlab.com/$IMAGE:$CI_COMMIT_SHA || true

stages:
  - build
  - test
  - push
  - deploy

build_image:
  stage: build
  script:
  - if [ "$CACHE" = "yes" ]; then docker pull docker.io/$IMAGE:latest; fi
  - docker build --pull --cache-from docker.io/$IMAGE:latest --build-arg BUILDID=$CI_PIPELINE_ID --build-arg REPO_URL=$CI_PROJECT_URL -t registry.gitlab.com/$IMAGE:$CI_COMMIT_SHA .
  - docker push registry.gitlab.com/$IMAGE:$CI_COMMIT_SHA

pipenv_check:
  stage: test
  script:
  - docker run --rm registry.gitlab.com/$IMAGE:$CI_COMMIT_SHA check

pytest:
  stage: test
  script:
  - docker run --rm registry.gitlab.com/$IMAGE:$CI_COMMIT_SHA test

dockerhub:
  stage: push
  script:
  - docker tag registry.gitlab.com/$IMAGE:$CI_COMMIT_SHA docker.io/$IMAGE:latest
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push docker.io/$IMAGE:latest
  only:
    refs:
      - master

push_tagged_image:
  stage: push
  script:
  - docker tag registry.gitlab.com/$IMAGE:$CI_COMMIT_SHA docker.io/$IMAGE:$CI_COMMIT_TAG
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push docker.io/$IMAGE:$CI_COMMIT_TAG
  only:
    - tags

openshift:
  stage: deploy
  image:
    name: openshift/origin:v3.9
    entrypoint: ["/bin/sh", "-c"]
  before_script: []
  script:
  - oc login https://api.starter-us-west-2.openshift.com --token=$OPENSHIFT_TOKEN
  - oc project quedar
  - oc apply -f openshift
  - oc import-image quedar
  - oc rollout status dc/quedar -w
  only:
    refs:
      - master
  environment:
    name: production
    url: http://quedar-quedar.7e14.starter-us-west-2.openshiftapps.com
