image: docker:stable
variables:
  DOCKER_DRIVER: overlay2
  IMAGE: vrutkovs/quedar
  DOCKER_USERNAME: vrutkovs
  GITLAB_USERNAME: vrutkovs
services:
- docker:dind

stages:
  - build
  - test
  - push
  - deploy

build_image:
  stage: build
  script:
  - docker build --build-arg BUILDID=$CI_PIPELINE_ID --build-arg REPO_SLUG=$CI_PROJECT_PATH -t registry.gitlab.com/$IMAGE .
  - docker login -u="GITLAB_USERNAME" -p="$GITLAB_TOKEN" registry.gitlab.com
  - docker push registry.gitlab.com/$IMAGE

pipenv_check:
  stage: test
  script:
  - docker pull registry.gitlab.com/$IMAGE
  - docker run --rm registry.gitlab.com/$IMAGE check

pytest:
  stage: test
  script:
  - docker pull registry.gitlab.com/$IMAGE
  - docker run --rm registry.gitlab.com/$IMAGE check

dockerhub:
  stage: push
  script:
  - docker pull registry.gitlab.com/$IMAGE
  - docker tag registry.gitlab.com/$IMAGE docker.io/$IMAGE
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push docker.io/$IMAGE
  only:
    refs:
      - master

push_tagged_image:
  stage: push
  script:
  - docker pull registry.gitlab.com/$IMAGE
  - docker tag registry.gitlab.com/$IMAGE docker.io/$IMAGE:$CI_COMMIT_TAG
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push docker.io/$IMAGE:$CI_COMMIT_TAG
  only:
    - tags

openshift:
  stage: deploy
  image: openshift/origin:v3.9
  script:
  - oc login https://api.starter-us-west-2.openshift.com --token=$OPENSHIFT_TOKEN
  - oc project quedar
  - oc apply -f openshift
  - oc import-image quedar
  - oc rollout status dc/quedar -w
  only:
    refs:
      - master
  environment:
    name: production
    url: http://quedar-quedar.7e14.starter-us-west-2.openshiftapps.com
