image: docker:stable
variables:
  DOCKER_DRIVER: overlay2
services:
- docker:dind

stages:
  - build
  - check
  - test
  - push
  - deploy

build_image:
  stage: build
  script:
  - docker build --build-arg BUILDID=$TRAVIS_BUILD_ID --build-arg REPO_SLUG=$TRAVIS_REPO_SLUG -t vrutkovs/quedar .

pipenv_check:
  stage: check
  script:
  - docker run --rm --entrypoint=make -ti vrutkovs/quedar check

pytest:
  stage: test
  script:
    - docker run --rm --entrypoint=make -ti vrutkovs/quedar test

push_image:
  stage: push
  script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push vrutkovs/quedar
  only:
    refs:
      - master

push_tagged_image:
  stage: push
  script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag vrutkovs/quedar:latest vrutkovs/quedar:"$TAG"
  - docker push vrutkovs/quedar:"$TAG"
  only:
    - tags

deploy_to_starter:
  stage: deploy
  script:
  - wget https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-$OC_VERSION-linux-64bit.tar.gz
  - tar -xvf openshift-origin-client-tools-$OC_VERSION-linux-64bit.tar.gz
  - mv openshift-origin-client-tools-$OC_VERSION-linux-64bit oc
  - export PATH=`pwd`/oc:$PATH
  - oc login https://api.starter-us-west-2.openshift.com --token=$OPENSHIFT_TOKEN
  - oc project quedar
  - oc apply -f openshift
  - oc import-image quedar
  - oc rollout status dc/quedar -w
  only:
    refs:
      - master
  environment:
    name: production
    url: http://quedar-quedar.7e14.starter-us-west-2.openshiftapps.com
