image: docker:stable
variables:
  DOCKER_DRIVER: overlay2
  IMAGE: vrutkovs/quedar
services:
- docker:dind

stages:
  - build
  - test
  - push
  - deploy

build_image:
  stage: build
  script:
  - docker build --build-arg BUILDID=$CI_PIPELINE_ID --build-arg REPO_SLUG=$CI_PROJECT_PATH -t registry.gitlab.com/$IMAGE .
  - docker push registry.gitlab.com/$IMAGE

pipenv_check:
  stage: test
  script:
  - docker pull registry.gitlab.com/$IMAGE
  - docker run --rm registry.gitlab.com/$IMAGE check

pytest:
  stage: test
  script:
  - docker pull registry.gitlab.com/$IMAGE
  - docker run --rm registry.gitlab.com/$IMAGE check

push_to_dockerhub:
  stage: push
  script:
  - docker pull registry.gitlab.com/$IMAGE
  - docker tag registry.gitlab.com/$IMAGE docker.io/$IMAGE
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push docker.io/$IMAGE
  only:
    refs:
      - master

push_tagged_image:
  stage: push
  script:
  - docker pull registry.gitlab.com/$IMAGE
  - docker tag registry.gitlab.com/$IMAGE docker.io/$IMAGE:$CI_COMMIT_TAG
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push docker.io/$IMAGE:$CI_COMMIT_TAG
  only:
    - tags

deploy_to_starter:
  stage: deploy
  script:
  - wget https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-$OC_VERSION-linux-64bit.tar.gz
  - tar -xvf openshift-origin-client-tools-$OC_VERSION-linux-64bit.tar.gz
  - mv openshift-origin-client-tools-$OC_VERSION-linux-64bit oc
  - export PATH=`pwd`/oc:$PATH
  - oc login https://api.starter-us-west-2.openshift.com --token=$OPENSHIFT_TOKEN
  - oc project quedar
  - oc apply -f openshift
  - oc import-image quedar
  - oc rollout status dc/quedar -w
  only:
    refs:
      - master
  environment:
    name: production
    url: http://quedar-quedar.7e14.starter-us-west-2.openshiftapps.com
