language: python
python:
  - "3.6"
install:
  - pip install pipenv
env:
  - DOCKER_IMAGE=vrutkovs/quedar OC_VERSION=v3.9.0-191fece OC_PROJECT=quedar OC_IMAGESTREAM=quedar OC_DEPLOYMENTCONFIG=quedar

stages:
  - pipenv
  - "docker image"
  - "docker tag image"
    if: tag IS present
  - name: "deploy to Origin"
    if: branch = master AND type = push

jobs:
  include:
    - stage: pipenv
      script:
      - pipenv check
      - pipenv install --system --deploy
    - stage: "docker image"
      script:
      - docker build -t $DOCKER_IMAGE .
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker push $DOCKER_IMAGE
    - stage: "docker tag image"
      script:
      - docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$TRAVIS_TAG
      - docker push $DOCKER_IMAGE:$TRAVIS_TAG
    - stage: "deploy to Origin"
      script:
      - wget https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-$OC_VERSION-linux-64bit.tar.gz
      - tar -xvf openshift-origin-client-tools-$OC_VERSION-linux-64bit.tar.gz
      - mv openshift-origin-client-tools-$OC_VERSION-linux-64bit oc
      - export PATH=`pwd`/oc:$PATH
      - oc login https://api.starter-us-west-2.openshift.com --token=$OPENSHIFT_TOKEN
      - oc project $OC_PROJECT
      - oc import-image $OC_IMAGESTREAM
      - oc rollout status dc/$OC_DEPLOYMENTCONFIG -w
notifications:
  email: false
