language: python
python:
  - "3.6"
install:
  - pip install pipenv
script:
  - pipenv check
  - pipenv install --system --deploy
after_success:
  #Push to docker
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    docker build -t vrutkovs/quedar . &&
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
    docker push vrutkovs/quedar
    fi
  #Rollout new openshift deployment
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    wget https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz &&
    tar –xvf openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz
    mv openshift-origin-client-tools-v3.9.0-191fece-linux-64bit oc
    export PATH=`pwd`/oc:$PATH
    oc login https://api.starter-us-west-2.openshift.com --token=$OPENSHIFT_TOKEN
    oc project quedar
    oc import-image quedar
    oc rollout latest dc/quedar
    fi
notifications:
  email: false
