language: python
python:
  - "3.6"
install:
  - pip install pipenv
env:
  - DOCKER_IMAGE=vrutkovs/quedar OC_VERSION=v3.9.0-191fece

stages:
  - pipenv
  - unittests
  - name: "deploy to Origin"
    if: branch = master AND type = push AND fork = false

jobs:
  include:
    - stage: pipenv
      script:
      - pipenv check

    - stage: unittests
      script:
      - docker build --build-arg BUILDID=$TRAVIS_BUILD_ID --build-arg REPO_SLUG=$TRAVIS_REPO_SLUG -t $DOCKER_IMAGE .
      - docker run --rm --entrypoint=tests/run.sh -ti $DOCKER_IMAGE
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker push $DOCKER_IMAGE

    - stage: "deploy to Origin"
      script:
      - wget https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-$OC_VERSION-linux-64bit.tar.gz
      - tar -xvf openshift-origin-client-tools-$OC_VERSION-linux-64bit.tar.gz
      - mv openshift-origin-client-tools-$OC_VERSION-linux-64bit oc
      - export PATH=`pwd`/oc:$PATH
      - oc login https://api.starter-us-west-2.openshift.com --token=$OPENSHIFT_TOKEN
      - oc project quedar
      - oc apply -f openshift
      - oc import-image quedar
      - oc rollout status dc/quedar -w

notifications:
  email: false
