apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: quedar
  name: quedar
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: 'docker.io/vrutkovs/quedar:latest'
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
